### ISSUE TITLE
advertisement-discovery.js not detecting con-connectable peripheral

### ISSUE THREAD

**Issue by electronut** [sandeepmistry/noble#589] opened 2017-04-04 10:19 UTC
On a Raspberry Pi 3 with bluez installed, I can run the following and detect my BLE device which is running on a non-connectable advertising mode:

```
sudo hcitool lescan
```

But when I run:

```
sudo node advertisement-discovery.js
```

I don't see the above device. I am able to see other connectable BLE devices.

Any idea what might be going on? Thanks.

**Comment by electronut** [comment] 2017-04-07 06:17
Anyone? 

The above can be tested by running the `ble_app_beacon` Nordic example on the nRF52-DK.

**Comment by sandeepmistry** [comment] 2017-04-17 00:19
@electronut see https://github.com/sandeepmistry/noble/issues/594#issuecomment-294382410.

Closing as a duplicate of #594 .

**Closed by sandeepmistry** 2017-04-17 00:19 UTC
