### ISSUE TITLE
Error connecting to multiple peripherals

### ISSUE THREAD

**Issue by qrazhan** [sandeepmistry/noble#143] opened 2015-03-05 08:58 UTC
I'm having trouble connecting to multiple peripherals.  I can connect to one just fine, but once I try and connect to a second device I get the error "Transport endpoint is not connected".  Any ideas what could be wrong here?  I'm using bluez 5.28 on a Raspberry Pi.

**Comment by sandeepmistry** [comment] 2015-03-05 23:50
@qrazhan this is a duplicate of https://github.com/sandeepmistry/noble/issues/104 I should have time to take another look at it on the weekend.

**Closed by sandeepmistry** 2015-03-05 23:50 UTC
Labels: duplicate
