### ISSUE TITLE
XPC binding broken on MacOS 10.13 (High Sierra)

### ISSUE THREAD

**Issue by pavel-zdenek** [sandeepmistry/noble#735] opened 2018-01-11 13:55 UTC
From what i found out quickly, BLE state change is now id 4 not 6, and when i changed just that to start scanning, next received message was id 29, which is not in the currently handled ids either. I guess this approach is not long term sustainable, which is probably why you started effort branch `core-bluetooth`. I have seen your comment somewhere, that you plan to merge the branch, but it is 1.5yrs old now. I have a mild interest in getting it working on MacOS, so can you tell me what is the state of the branch and its mergeability by an outsider?

**Comment by jacobrosenthal** [comment] 2018-01-11 17:35
Duplicate of https://github.com/sandeepmistry/noble/issues/679

**Closed by jacobrosenthal** 2018-01-11 17:35 UTC
