### ISSUE TITLE
Not working after macOS High Sierra Upgrade

### ISSUE THREAD

**Issue by dlarendt** [sandeepmistry/noble#709] opened 2017-11-02 22:48 UTC
Noble was working on my system recently, but it is no longer working after I upgraded to macOS High Sierra this morning. Running examples/advertisement-discovery.js produces no output. I am sure there are bluetooth devices in range. Any ideas on how to start troubleshooting this?

**Comment by bennesp** [comment] 2017-11-05 13:44
The same is happening to me, with Apple Bluetooth Explorer I can see many BLE devices, but advertisement-discovery.js shows me nothing

**Comment by dlarendt** [comment] 2017-11-09 22:50
Yep, worked for me too.

**Comment by jguillod** [comment] 2017-12-01 15:47
Dont work for me under High Sierra !!
Was working perfectly just before !

**Comment by jacobrosenthal** [comment] 2017-12-23 19:55
Duplicate of #679

**Closed by jacobrosenthal** 2017-12-23 19:55 UTC
