### ISSUE TITLE
Add Buffer shim from NPM

### ISSUE THREAD

**Issue by rclai** [sandeepmistry/noble#388] opened 2016-04-24 21:12 UTC
I'm trying to integrate `noble` into React Native by simply installing this library and then feeding the Noble constructor with custom bindings, however, the React Native bridge doesn't allow bridging of Buffer objects and must first be sent as base-64 encoded strings to the iOS Objective-C world/Android Java world and be decoded into NSData/[Java Equivalent NSData].

I know I could just pass a Buffer, convert to base-64 string in the custom bindings then send it to the bridge, but that would be unnecessary overhead.

That said, would you be okay with moving the Buffer type check from `Characteristic.prototype.write` to be at the bindings level?

**Comment by sandeepmistry** [comment] 2016-04-24 22:50
@rclai I'm not too keen about this.

What's your goal for porting noble to React Native? Requiring a base-64 string for data args would introduce incompatibilities, if people wanted to run existing noble code. I think converting buffer's to/from base64 in the binding layer is ok.

**Comment by rclai** [comment] 2016-04-24 22:56
No, I'm not saying to pass data always as base-64 strings. I'm saying to just simply remove [this check](https://github.com/sandeepmistry/noble/blob/67a00d1eddb7339ba5d135f9830d7a79441545a5/lib/characteristic.js#L52-L56) so that you can pass whatever you want. The other bindings will continue to require passing in Buffers.

**Comment by rclai** [comment] 2016-04-24 23:27
Actually, never mind this. I did not have a good understanding of Buffer objects and how they're converted to NSData. Now I understand.

**Comment by rclai** [comment] 2016-04-25 22:29
Hey @sandeepmistry, sorry I'd like to revisit this again but this time it's for a different purpose.

So I figured out how to create a Buffer object in React Native, however, I found out that React Native doesn't have a global `Buffer` object, so every time it hits this [code](https://github.com/sandeepmistry/noble/blob/67a00d1eddb7339ba5d135f9830d7a79441545a5/lib/characteristic.js#L52-L56), it breaks.

So I had to overwrite the prototype function to not check for it like [this](https://github.com/Profab/react-native-ble/commit/cffe68d430b9a1649e4122250bd7961b60febce2). I am not fond of this, but would you be open to adding a `Buffer` shim at the top of the `characteristic.js` file which will do something like this:

```js
var Buffer = (window || global).Buffer || require('buffer').Buffer;
```

**Comment by rclai** [comment] 2016-04-26 23:55
Ping @sandeepmistry.

**Comment by sandeepmistry** [comment] 2016-04-28 22:55
I'm not opposed to merging this, but we should take a look at the bigger picture.

Is there any way the Reactive Native bride could inject Buffer into global/window scope? This would be a big win for the existing packages that depend on noble: https://www.npmjs.com/browse/depended/noble -  they in theory would work as is.

cc/ @jacobrosenthal

**Comment by jacobrosenthal** [comment] 2016-04-29 04:28
I think the issue is the the react package manager can only alias with the browser keyword 1 level deep, unlike the webpack which will swap packages n-deep. the Please upvote both of these:
https://productpains.com/post/react-native/packager-support-resolvealias-ala-webpack/ https://github.com/facebook/react-native/issues/6253

**Comment by sandeepmistry** [comment] 2016-05-09 00:50
@jacobrosenthal upvoted. I'm going to close this for now.

**Closed by sandeepmistry** 2016-05-09 00:50 UTC
Labels: question

**Comment by windhost** [comment] 2016-09-02 07:08
@rclai I meet the same problem, could you tell me how to create a Buffer object in React Native?

**Comment by windhost** [comment] 2016-09-02 09:08
@rclai I solved it ,by 

 `var Buffer = (window || global).Buffer || require('buffer').Buffer;`

thanks a lot
