### ISSUE TITLE
Segfault occurs on OS X Yosemite

### ISSUE THREAD

**Issue by tompropst** [sandeepmistry/noble#102] opened 2014-11-12 16:24 UTC
If I call startScanning() and do not call stopScanning(), what would cause the script to terminate?  My script usually will run indefinitely but does stop unexpectedly at times.  I suspect it could be related to connection reliability to discovered peripherals or lack of connected peripherals but I'm not always seeing disconnect events.
I am:
1. startScanning() and continue scanning for new / disconnected peripherals
2. connect to some discovered peripherals (not all)
3. subscribe to notifications of the target peripherals
4. read data from the target peripherals on notifications (about 1 / minute)

I'm testing on OS X.

**Comment by sandeepmistry** [comment] 2015-01-04 15:29
@tompropst thanks, it would be great if we can reproduce this faster (I haven't had time to try out your script for more than a few hours, as I only have one Mac).

**Comment by tompropst** [comment] 2015-01-06 16:21
@sandeepmistry, I ran a few tests with various scanning / "resting" times. The issue definitely appears faster the more scanning you are doing so I recommend scanning continuously to get to the error as quickly as possible.  It may still take several hours in my experience.

If there is any more debug information that I can collect for you, just let me know.

**Comment by sandeepmistry** [comment] 2015-01-07 00:00
@tompropst I'll try it out over night ...

Is the following enough to reproduce?

```javascript
var noble = require('../index');

noble.on('stateChange', function(state) {
  if (state === 'poweredOn') {
    noble.startScanning([], true);
  } else {
    noble.stopScanning();
  }
});

noble.on('discover', function(peripheral) {
  console.log('peripheral discovered (' + peripheral.uuid+ '):');
});
```

Did you have a chance to look at the memory usage?

**Comment by tompropst** [comment] 2015-01-07 02:18
I will try running the above script now and monitor memory usage.  I believe it should exhibit the same issue.  I have looked casually at memory usage in the past and it was increasing over time but not an alarming amount.

**Comment by sandeepmistry** [comment] 2015-01-07 03:00
@tompropst going to start an overnight test now, included ```segfault_handler``` and logging date on discover as well.

**Comment by sandeepmistry** [comment] 2015-01-07 11:44
@tompropst no segfault yet, Activity Monitor reports node is using 11 MB of memory:

 * Real Memory: 7.8 MB
 * Virtual Memory: 2.91 GB
 * Shared Memory: 224 KB
 * Private Memory: 6.1 MB

I'll run again tonight with more devices in range.

**Comment by sandeepmistry** [comment] 2015-01-07 22:52
@tompropst still running on my Mac, left it on during the day. I am using noble 0.3.7 from source, which has been upgraded to using node-xpc-connect v0.1.0

```javascript
var SegfaultHandler = require('segfault-handler');

SegfaultHandler.registerHandler();

var noble = require('../index');

noble.on('stateChange', function(state) {
  if (state === 'poweredOn') {
    noble.startScanning([], true);
  } else {
    noble.stopScanning();
  }
});

noble.on('discover', function(peripheral) {
  console.log(new Date());
  console.log('peripheral discovered (' + peripheral.uuid+ '):');
  console.log('\thello my local name is:');
  console.log('\t\t' + peripheral.advertisement.localName);
  console.log('\tcan I interest you in any of the following advertised services:');
  console.log('\t\t' + JSON.stringify(peripheral.advertisement.serviceUuids));

  var serviceData = peripheral.advertisement.serviceData;
  if (serviceData && serviceData.length) {
    console.log('\there is my service data:');
    for (var i in serviceData) {
      console.log('\t\t' + JSON.stringify(serviceData[i].uuid) + ': ' + JSON.stringify(serviceData[i].data.toString('hex')));
    }
  }
  if (peripheral.advertisement.manufacturerData) {
    console.log('\there is my manufacturer data:');
    console.log('\t\t' + JSON.stringify(peripheral.advertisement.manufacturerData.toString('hex')));
  }
  if (peripheral.advertisement.txPowerLevel !== undefined) {
    console.log('\tmy TX power level is:');
    console.log('\t\t' + peripheral.advertisement.txPowerLevel);
  }

  console.log();
});
```

**Comment by sandeepmistry** [comment] 2015-01-08 11:46
@tompropst still no segfault on my test, I haven't stopped the process from the overnight test.

Real Memory: 12.8 MB
Virtual Memory: 2.91 GB
Shared Memory: 224 KB
Private Memory: 12.1 MB

Also, added an Arduino device that advertises every 100ms.

**Comment by tompropst** [comment] 2015-01-08 22:48
That's odd. The only difference I see is that I am calling ```startScanning()``` with no duplicates.  My Mac is also circa 2011.  Maybe it is an issue with that BT driver / HW.

I'm happy to keep working on this and can try to take a more active role since it only occurs on my system.  I'm OK with closing this too if you'd like.  My primary platform is Linux.

**Comment by sandeepmistry** [comment] 2015-01-09 02:12
Have you done a fresh npm install of noble since upgrading OS X and/or node?

**Comment by tompropst** [comment] 2015-01-09 02:54
I haven't since a few days before opening this issue.  I started using noble on 11/7.  I haven't upgraded OS X since then but I can't say for sure about node.

I'll update now and run another test.

**Comment by tompropst** [comment] 2015-01-09 14:20
I updated to noble 0.3.7 last night and the test has been running for 11 hours with no crash. I'll leave it running as long as I can.

**Comment by sandeepmistry** [comment] 2015-01-10 00:01
Interesting, maybe the conversion to using NAN fixed something (see https://github.com/sandeepmistry/node-xpc-connection/pull/6)

**Comment by sandeepmistry** [comment] 2015-02-08 18:02
@tompropst closing now, as you appear to be crash free.

**Closed by sandeepmistry** 2015-02-08 18:02 UTC
